import {
  type CreateOrder,
  orderListSchema,
  orderQuoteSchema,
  orderSchema,
  type QuoteOrder,
} from '@petdots/contracts';

import type { HttpClient } from './http';

/** Every call here is the caller's own data, so every one of them sends the token. */
const AUTHED = { auth: true } as const;

/**
 * Prices the cart without creating anything.
 *
 * `signal` matters more here than anywhere else: the checkout re-quotes on
 * every change of quantity, and an answer that arrives after the next one would
 * overwrite a newer total with an older one.
 */
export function quoteOrder(http: HttpClient, body: QuoteOrder, signal?: AbortSignal) {
  return http
    .postJson('/order-quotes', body, { ...AUTHED, signal })
    .then((it) => orderQuoteSchema.parse(it));
}

/**
 * Creates the order.
 *
 * The key is generated by the screen when the checkout opens and kept until the
 * order succeeds, so every retry of the *same* attempt carries the same key and
 * a genuinely new order gets a new one.
 */
export function placeOrder(http: HttpClient, body: CreateOrder, idempotencyKey: string) {
  return http
    .postJson('/orders', body, { ...AUTHED, headers: { 'Idempotency-Key': idempotencyKey } })
    .then((it) => orderSchema.parse(it));
}

export function listMyOrders(http: HttpClient, signal?: AbortSignal) {
  return http
    .getJson('/orders', undefined, { ...AUTHED, signal })
    .then((body) => orderListSchema.parse(body).items);
}

export function findMyOrder(http: HttpClient, orderId: string, signal?: AbortSignal) {
  return http
    .getJson(`/orders/${orderId}`, undefined, { ...AUTHED, signal })
    .then((body) => orderSchema.parse(body));
}

/** Cancels, up to the moment the store accepts. Answers the order in its new state. */
export function cancelMyOrder(http: HttpClient, orderId: string) {
  return http
    .postJson(`/orders/${orderId}/cancellation`, {}, AUTHED)
    .then((it) => orderSchema.parse(it));
}
